-- Migración: Notificaciones comerciales por agente (CRM)
-- Fecha: 2026-08-08
-- Idempotente: se puede ejecutar varias veces sin errores.
-- Tipos alineados con el código del proyecto (crm_config_agente, crm_leads, agentes_ia, conversaciones).

-- 0) Limpieza de policies RLS duplicadas en crm_config_agente.
-- El proyecto lee/escribe con la service role (bypassa RLS), así que estas policies
-- no afectan el funcionamiento. Supabase Studio puede generarlas con nombres como
-- "crm_config_agente_update_own" y al re-ejecutar este script darían error 42710.
drop policy if exists "crm_config_agente_update_own" on public.crm_config_agente;
drop policy if exists "crm_config_agente_insert_own" on public.crm_config_agente;
drop policy if exists "crm_config_agente_select_own" on public.crm_config_agente;
drop policy if exists "crm_config_agente_delete_own" on public.crm_config_agente;

-- 1) Campos de configuración de notificaciones en crm_config_agente
alter table public.crm_config_agente
    add column if not exists notify_on_intent boolean not null default false,
    add column if not exists notify_on_payment boolean not null default false,
    add column if not exists notify_on_state_change boolean not null default false,
    add column if not exists notify_channels text[] not null default '{}'::text[],
    add column if not exists notify_recipients text[] not null default '{}'::text[],
    add column if not exists notify_cc_agent boolean not null default true,
    add column if not exists notify_attach_receipt boolean not null default false,
    add column if not exists notify_webhook_url text;

-- 2) Tabla de trazabilidad de notificaciones (envíos y errores)
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid,
    agente_id bigint,
    lead_id bigint,
    conversation_id uuid,
    event_type text not null,
    channel text not null default 'email',
    recipient text,
    subject text,
    status text not null default 'pending',
    external_id text,
    error text,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

-- Índices de consulta (historial por agente / lead / fecha)
create index if not exists notifications_agente_id_idx on public.notifications (agente_id);
create index if not exists notifications_lead_id_idx on public.notifications (lead_id);
create index if not exists notifications_created_at_idx on public.notifications (created_at desc);

-- RLS: por defecto activa solo para el servicio. Si el proyecto usa RLS por usuario,
-- descomentar y ajustar según las políticas existentes del resto de tablas.
-- alter table public.notifications enable row level security;
